### ISSUE TITLE
vio  modules or slam modules. which matters?

### ISSUE THREAD

**Issue by wolf943134497** [SpectacularAI/HybVIO#16]
Hi @oseiskar  Thanks for your great works!

Your algorithm outperform the current state-of-the-art. Have you test other VIO + slam modules, like MSCKF vins-mono etc.
I would like to know which one  is important vio  modules or  slam modules?

**Comment by oseiskar** [comment]
We have not tested other VIO + SLAM module combinations in this codebase. They do not have common APIs so testing each combination would require a rather significant amount of software development.
