### ISSUE TITLE
cmake problem

### ISSUE THREAD

**Issue by dean1314** [SpectacularAI/HybVIO#17]
hello
Thank for you sharing so good job
I build on ubuntu1804 system
When I cmake the project after finished the build.sh file, I encoutered the problem so follow:
![Selection_144](https://user-images.githubusercontent.com/16264780/162555540-f537429b-e9a2-482f-86c2-303b381252b7.png)

**Comment by oseiskar** [comment]
Seems like [this symlink](https://github.com/AaltoML/mobile-cv-suite/blob/da7c2aea38dcb4085ef10e7414c8b96e2bbcc85f/mobile-cv-suite-config.cmake) is not working on your machine for some reason. I would first recommend making a fresh clone with `git clone --recrusive https://github.com/SpectacularAI/HybVIO.git` and, if that does not help, then installing a more recent version of CMake

**Comment by dean1314** [comment]
thanks, I've solved this issue.

**Comment by X-NEARS** [comment]
could you tell me how to solve this same problem, thanks a lot

gcc    -O3 -fexceptions -fPIC "" -c SuiteSparse_config.c
gcc: error: : There is no such file or directory
Makefile:28: recipe for target 'SuiteSparse_config.o' failed
make: *** [SuiteSparse_config.o] Error 1
