### ISSUE TITLE
The trajectory of VIO is easy to drift

### ISSUE THREAD

**Issue by dean1314** [SpectacularAI/HybVIO#18]
hello
I used D1000-120 model of mynteye  camera and recorded a ten minutes data by fixed it on the front of car.  Then I used the convert way mentioned in your readme file.  Finally, I used "./main -i=my-data-path -p" command in the terminal and run it.  But the trajectory is easy to drift. so do you have any try on mynteye  camera?

**Comment by oseiskar** [comment]
We do not offer support for troubleshootining the performance of the method for different devices in this open source repository. For commercial support, you can contact us at https://www.spectacularai.com/
