### ISSUE TITLE
question about a jacobian

### ISSUE THREAD

**Issue by fushi219** [SpectacularAI/HybVIO#24]
Hi! Thanks for your beautiful code and I am confused about a jacobian and wish to get your help.

I  have no idea about jacobians from [https://github.com/SpectacularAI/HybVIO/blob/main/src/odometry/triangulation.cpp#L270](url) to [https://github.com/SpectacularAI/HybVIO/blob/main/src/odometry/triangulation.cpp#L322](url). Are these calculations  used for jacobian of landmark reprojection errors to imu poses in ekf state, which will be used in later filter update? (in this way, we do not need to project H into nullspaces of landmark.)  But how the jacobians are derivated?

I know its quite boring and troublesome to explain it, so a liitle explain will be grateful,  thanks!

**Comment by oseiskar** [comment]
Hello. You are correct, those Jacobians are intermediary steps and the goal is computing the Jacobian of the reprojection errors accurately (by differentiating an entire Gauss-Newton iteration process) so the MSCKF nullspace projection trick is not needed. This is the main difference between [PIVO](https://aaltovision.github.io/PIVO/) and MSCKF. HybVIO is a derivative of the PIVO method in this sense.

What it actually differentiated in [that code block](https://github.com/SpectacularAI/HybVIO/blob/e325353846d9026de6001f593134bed77824469d/src/odometry/triangulation.cpp#L321-L322) are (related to) the left and right hand side of a Gauss-Newton update step in the triangulation process.

**Comment by fushi219** [comment]
Thanks a lot! I have understood the jacobians mentioned above, however, i can't figure out these: https://github.com/SpectacularAI/HybVIO/blob/e325353846d9026de6001f593134bed77824469d/src/odometry/triangulation.cpp#L337-L338 wish to get some help. Thanks!
