### ISSUE TITLE
Question about a jacobian

### ISSUE THREAD

**Issue by fushi219** [SpectacularAI/HybVIO#25]
What do these two following lines mean? 

https://github.com/SpectacularAI/HybVIO/blob/e325353846d9026de6001f593134bed77824469d/src/odometry/triangulation.cpp#L337-L338

Thanks!

**Comment by oseiskar** [comment]
Hi @fushi219. We unfortuntately cannot spend more time explaining the code line by line (ref #23 , #24). The overall purpose of the method is explained in the PIVO paper and the there is a [unit test](https://github.com/SpectacularAI/HybVIO/blob/main/test/triangulation.cpp) to verify that the formulas for the derivatives are correct. Each step follows from, e.g., chain rule of differentation or other generic (linear-algebraic) differentiation formulas
