### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by Gatsby23** [SpectacularAI/HybVIO#33]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/18000675/193836265-be1851af-a47d-4aeb-816a-ab592b88c9c4.png">
Dear professor:
In the experiment part, you have mentioned to read the app for more details, but I don't know where to find the app, could you please give me some advice?
Yours

**Comment by ArmandB** [comment]
https://arxiv.org/pdf/2106.11857.pdf page 11
