### ISSUE TITLE
Question about the parameters

### ISSUE THREAD

**Issue by DrZ-21** [SpectacularAI/HybVIO#35]
Dear sir,
     Thanks for the excellent work! 
     i have a question about the parameters "-maxVisualUpdates" and "-maxSuccessfulVisualUpdates",their default value are both 20.When i set them both to 30,the mono vio can also run in realtime in euroc, but the result seems to be the same as the 20's.Is that right?But I think that the more visual updates are done,the better result that we should get. 
    Thanks again!

**Comment by oseiskar** [comment]
Not unexpected. Diminishing returns and random variation.

**Comment by DrZ-21** [comment]
Excuse me,sir.What does "Diminishing returns" mean?

**Comment by oseiskar** [comment]
It means that when you increase some parameter from 5 to 10, the effect is significant, when you increase it from 10 to 20 the positive effect is smaller but noticeable, and when you increase from 20 to 30 or beyond, the positive effect is so small that it gets lost in the random noise. This is a common pheonomenon in many contexts.

**Comment by DrZ-21** [comment]
I got it and thank you!
