### ISSUE TITLE
Question about distortion coefficients

### ISSUE THREAD

**Issue by DrZ-21** [SpectacularAI/HybVIO#36]
Dear sir,
Thanks for the excellent work! i have a little question about the distortion coefficients.In euroc dataset the parameter.txt is using the third parameter as k3.But according to the radial-tangential distortion model,its origin meaning is p1,is that right?So it confuses me.Waiting for your reply,thanks again!

**Comment by DrZ-21** [comment]
Dear sir,
Thanks for the excellent work! i have a little question about the distortion coefficients.In euroc dataset the parameter.txt is using the third parameter as k3.But according to the radial-tangential distortion model,its origin meaning is p1,is that right?So it confuses me.Waiting for your reply,thanks again!

**Comment by oseiskar** [comment]
https://github.com/SpectacularAI/HybVIO/issues/38#issuecomment-1283571739
