### ISSUE TITLE
Question about jacobian in triangulation

### ISSUE THREAD

**Issue by fushi219** [SpectacularAI/HybVIO#38]
Hi, i am confused about the following code:

https://github.com/SpectacularAI/HybVIO/blob/main/src/odometry/triangulation.cpp#L337

Thanks a lot!

**Comment by oseiskar** [comment]
Hi @fushi219 . Unfortunately, we do not have the resources to use the issue tracker in this repository as a general Q&A about the algorithm details. We will not answer questions like this in the future.
