### ISSUE TITLE
Can't compile on any of the systems

### ISSUE THREAD

**Issue by Meister1593** [SpectacularAI/HybVIO#39]
On arch with dependencies - issue with definitions in opencv for ffmpeg
On debian (same as in description) it gives compile error around json library area
On ubuntu 22.04 there is another error (can't remember as of now)

what i'm doing wrong? i can't compile dependencies on any of the systems
in case logs needed, i can provide them, but they are all from 3rd party dependencies (mobile cv)

**Comment by oseiskar** [comment]
> On ubuntu 22.04 there is another error (can't remember as of now)

Hi, this is not the way to report an issue. See https://stackoverflow.com/help/minimal-reproducible-example and re-open

**Comment by Meister1593** [comment]
i was so confused about the reproducing the build at all
all examples of installing dependencies and then trying to compile projects (dependencies) were failed for me
