### ISSUE TITLE
question about the processing queues

### ISSUE THREAD

**Issue by DrZ-21** [SpectacularAI/HybVIO#40]
Dear sir
     Thanks for the excellent work! This code has two queues to perform feature detection or tracking things in one thread(the first queue)  and do ekf works like propogations or visual updates in the second thread(the second queue),is that right?Could you give some advice if i want to get two queues which are both to process images and parallel to each other before the ekf queue?Thanks a lot!

**Comment by oseiskar** [comment]
Hello. We do not give instructions like this in the issue tracker anymore.
