### ISSUE TITLE
Problem with triangulation【More importantly about how to understand PIVO】？

### ISSUE THREAD

**Issue by Gatsby23** [SpectacularAI/HybVIO#42]
Dear Professor：
         Recently, I have read the paper 《HybVIO: Pushing the Limits of Real-time Visual-inertial Odometry》and its corresponding code. Thank you for your wonderful work that contributes to the robotics community. However, there are some troubles bothering me a lot. I have noticed that the visual landmark estimation part(https://github.com/SpectacularAI/HybVIO/blob/main/src/odometry/triangulation.cpp#L203) is different from the triangulation part in the original msckf. That's the beauty of the PIVO, your previous paper, Right？ However, I don't understand, in the landmark triangulation part, why could you estimate the landmark coordinate jacobian with respect to the camera pose in the trail. To my knowledge, in this part, we would only estimate the landmark position and should calculate the jacobian with the landmark coordinate, like this: 
<img width="120" alt="image" src="https://user-images.githubusercontent.com/18000675/199037933-693aaf91-b6c4-4dec-a812-e6edcb53fcd8.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/18000675/199037965-c5a64f4e-1cda-45ce-ae1f-020806168dd4.png">
More precisely, I don't understand how to derive the analytical-formula of the jacobian dE^TE in the triangulation part. 
I have read your paper《PIVO: Probabilistic Inertial-Visual Odometry for Occlusion-Robust Navigation》  again and again. However, the paper is concise and I am not clever enough to understand why to calculate the jacobian like this. Could you please give me some doc or clues about it? I'm really looking forward for your help, thank you very much. 
Yours
Qi Wu

**Comment by oseiskar** [comment]
The idea of the Github repository is not to explain the mathematics behind the algorithm and we have recently decided that we do not elaborate these details on this forum anymore.

**Comment by Gatsby23** [comment]
> The idea of the Github repository is not to explain the mathematics behind the algorithm and we have recently decided that we do not elaborate these details on this forum anymore

Thank you for your quick reply, I'll send you email about this question. Thank you very much.
