### ISSUE TITLE
ROS wrapper

### ISSUE THREAD

**Issue by cmakelabs** [SpectacularAI/HybVIO#46]
I am wondering if there is a ROS wrapper already provided for HybVIO, since it is worth it to test it with live streams from a camera like RealSense T265 or other cameras through ROS topics

**Comment by oseiskar** [comment]
There is no ROS wrapper available and no plans to develop one in this codebase. We highly recommend using the [Spectacular AI SDK](https://spectacularai.github.io/docs/sdk/) instead of HybVIO for all live use cases
