### ISSUE TITLE
Run the algorithm live from camera

### ISSUE THREAD

**Issue by cmakelabs** [SpectacularAI/HybVIO#47]
I would like to know if it is possible to directly evaluate HybVIO live from an `intel realsense` camera stream of the camera, without the need of making records, the paper mentions online performance, but there does not seem to be a way to evaluate the performance online

**Comment by oseiskar** [comment]
There are no live examples in this codebase, but it is possible to implement them using this API https://github.com/SpectacularAI/HybVIO/blob/main/src/api/vio.hpp. However, I would not really recommend that in practice. The purpose of this codebase is academic reproducibility and it is not meant for production use. Trying to wrap this into an actual real-time product will send you down a rabbit hole of other issues, for which we will not provide free support here.

I warmly recommend the Spectacular AI SDK, which has better performance, APIs and supports several popular devices out-of-the-box (e.g., https://spectacularai.github.io/docs/sdk/wrappers/realsense.html).
