### ISSUE TITLE
Angular APE High - Issues w/ using pose for reprojection

### ISSUE THREAD

**Issue by ArmandB** [SpectacularAI/HybVIO#48]
I'm trying to use the output of HybVIO to do reprojection of past frame data onto the current frame, but when I try to do this, I get really large errors especially w.r.t. rotation.

To investigate further, I used https://github.com/uzh-rpg/rpg_trajectory_evaluation to get the angular APE on some sequences and saw it was really high. Below is the APE for euroc MH05. The translational APE matches the paper but the rotational APE is off by an average of 160 degrees.
![image](https://github.com/user-attachments/assets/154bd920-5390-4ef0-a291-7efb021f2cd7)

I am using the poses from output/euroc-mh-05-difficult.jsonl

Any idea what could be causing the error here? Are there any known bugs with the angular output of HybVIO?

**Comment by oseiskar** [comment]
This is probably a different coordinate systems in HybVIO vs https://github.com/uzh-rpg/rpg_trajectory_evaluation.

Note that there is no single standard or right answer to the question of how the "quaternion" in a "pose" is defined. There are > 100 different correct answers, depending on how your camera/local coordinate system, world coordinate system, quaternion convention and the direction of the transformation (w2c vs c2w) is defined.

HybVIO poses are either IMU-to-world or camera-to-world where camera follows the OpenCV convention and world is in Z-is-up convention (same as here https://spectacularai.github.io/docs/sdk/tracking.html#coordinate-systems).

In practice, you have to transform the coordinates in a multiplication like `q_c2w_fixed -> q_world_convention_change * q_c2w * q_local_local_convention_change`, where one or both of the "convention_change" rotations may be non-identity. If the ground truth alignment is SE3, `q_world_convention_change` can be left out.
