### ISSUE TITLE
ubuntu 20.4 undefined reference to `glfwInit'

### ISSUE THREAD

**Issue by 19920716** [SpectacularAI/HybVIO#5]
![image](https://user-images.githubusercontent.com/19903385/145371995-54080642-a1ae-4caa-8e4c-64b6792d535d.png)

**Comment by 19920716** [comment]
HybVIO/build/CMakeFiles/main.dir  link.txt add -lglfw，issues close。

**Comment by 19920716** [comment]
@oseiskar Thank you for telling me!

**Comment by oseiskar** [comment]
The proper fix to the issue is described here https://github.com/SpectacularAI/HybVIO#troubleshooting-disabling-gpu-visualizations-and-acceleration

**Comment by Michael-Zuo** [comment]
> The proper fix to the issue is described here https://github.com/SpectacularAI/HybVIO#troubleshooting-disabling-gpu-visualizations-and-acceleration

Thank you!
I notice this troubleshooting, but I was wandering if this change will disable the visualization function of this project.
